### PR TITLE
Setup pkg

### LINKED ISSUE #2: Setup initial package structure
As remarked in #1 @hsonne should setup a structure and make a PR from a dedicated branch. The master branch is already protected and a first test with travis worked.

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**
Setup the whole package again and add some files to .gitignore. Also removes the gitlab ci config.

This supersedes the #4 PR and hopefully gets rid if the init branch f***up #3 also closes #2, #5

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
Still needs:  

- a fixed R version? I think it is like this:

```yml
env:
   - TRAVIS_R_VERSION=3.5.2
```

- only one license file

**Comment by hsonne** [comment]
I think that the following (that was setup by @mrustl) checks on different R versions, an old and the current released version (I do not know which they are but assume that `release` refers to `3.5.2`) and the current development version:
```
r:
  - oldrel
  - release
  - devel
```
I would like to keep that.

**Comment by hsonne** [comment]
The markdown copy of the license file is required for the auto-generation of the documentation, so I would like to keep it even though it is just a duplicate.

**Comment by fabianmoronzirfas** [comment]
Okay. Cool. Let's keep it that way. I goes this is an approved review and I'll merge this now.

**Pull request merged**
