### PR TITLE
Added minimal io function for testing purpose

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**
This is a minimal function I would like to add for testing purpose.

@hsonne can you please review this and make it available from the package so I can start testing opencpu

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
The build failed:

```plain
The downloaded source packages are in
	‘/tmp/RtmpWIBG0C/downloaded_packages’
0.71s$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
Error in FUN(X[[i]], ...) : Invalid comparison operator in dependency: 
    jsonlite (>=1.6)
Calls: <Anonymous> -> local_package_deps -> lapply -> FUN
Execution halted
The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```

**Comment by fabianmoronzirfas** [comment]
Okay. I won't fix this. I need some help on this.

```plain
$ for name in $(find "${RCHECK_DIR}" -type f -name "*out");do echo ">>> Filename: ${name} <<<";cat ${name};done
>>> Filename: fhpredict.Rcheck/00install.out <<<
* installing *source* package ‘fhpredict’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : lexical error: invalid char in json text.
                                       NA
                     (right here) ------^
Error: unable to load R code in package ‘fhpredict’
Execution halted
ERROR: lazy loading failed for package ‘fhpredict’
* removing ‘/home/travis/build/technologiestiftung/fhpredict/fhpredict.Rcheck/fhpredict’
R CMD check failed
```

**Comment by hsonne** [comment]
The example below `@examples` should also not call `io()` because all examples are run during package build and running `io()` will block the process, I assume. Just comment the line in the example out: `#io()`

**Comment by hsonne** [comment]
I did some changes. Now, I do not get any errors when building the package.

**Comment by fabianmoronzirfas** [comment]
Cool. Looks like everything is fine. Can you approve the PR so we can merge? @hsonne

**Pull request merged**
